services:
  node:
    build:
      dockerfile: ./Dockerfile
      context: .
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:17.0-alpine
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=lottiemovie
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=VeryStrongPassword
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data
    command: ['redis-server', '--appendonly', 'yes']
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    command: ['server', '/data', '--console-address', ':9001']
    ports:
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data

volumes:
  postgres-data:
    driver: local
  minio-data:
    driver: local
  redis_data:
    driver: local
